show databases;
use customer_behaviour;
show tables;


select * from customer;

#--Q1. What is the total revenue generated by male vs. female customers?

select gender,sum(purchase_amount) as `total_revenue` from customer 
group by gender;

# --Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id,purchase_amount from customer
where discount_applied = 'yes'
and 
purchase_amount >= (select avg(purchase_amount) from customer);


# -- Q3. Which are the top 5 products with the highest average review rating?


select item_purchased,avg(review_rating) as `avg_rating` from customer
group by item_purchased 
order by avg_rating desc limit 5;


# --Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

SELECT 
    shipping_type,
    AVG(purchase_amount) AS avg_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


# --Q5. Do subscribed customers spend more? Compare average spend and total revenue 
# --between subscribers and non-subscribers.


select subscription_status,
count(customer_id) as `total_customer`,
avg(purchase_amount) as `avg_spend`,
sum(purchase_amount) as `total_revenue`
from customer 
group by subscription_status
order by total_revenue, avg_spend desc;

# ans : np



# --Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased ,
       AVG(discount_applied='Yes')*100 AS discount_percentage
FROM customer
GROUP BY item_purchased 
ORDER BY discount_percentage DESC
LIMIT 5;


# --Q7. Segment customers into New, Returning, and Loyal based on their total 
# -- number of previous purchases, and show the count of each segment. 


select
case 
	when previous_purchases = 1 then "New"
	when previous_purchases between 2 and 10 then "Returning"
	else "Loyal"
end as `customer_segement`,
count(*) as `no_of_customers` 
from customer 
group by customer_segement;


# --Q8. What are the top 3 most purchased products within each category? 

select category,item_purchased,count(*) as `item_count`
from customer 
group by item_purchased, category 
order by item_count desc limit 3;


SELECT category, item_purchased, count_item
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS count_item,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS rn
    FROM customer
    GROUP BY category, item_purchased
) t
WHERE rn <= 3;



# --Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?


select subscription_status,
count(customer_id) as `reapeat_buyer	`
from customer 
where previous_purchases  > 5
group by subscription_status ;


# --Q10. What is the revenue contribution of each age group? 


select age_group,
sum(purchase_amount) as `total_revenue`
from customer 
group by age_group
order by total_revenue desc;





























